import {
  CheckCircle2,
  FileSearch,
  GitCompareArrows,
  LoaderCircle,
  Siren,
  TimerReset,
} from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import CommitteeLayout from "@/components/CommitteeLayout";
import StatusBadge from "@/components/StatusBadge";
import { Card, CardContent } from "@/components/ui/card";
import useAuth from "@/hooks/useAuth";
import { apiRequest } from "@/lib/api";

const kpiConfig = [
  ["openReports", "Open Reports", FileSearch, "bg-blue-50 text-blue-600"],
  ["pendingReview", "Pending Review", TimerReset, "bg-amber-50 text-amber-600"],
  ["matchedCases", "Matched Cases", GitCompareArrows, "bg-purple-50 text-purple-600"],
  ["resolvedCases", "Resolved Cases", CheckCircle2, "bg-emerald-50 text-emerald-600"],
  ["sosRequests", "SOS Requests", Siren, "bg-red-50 text-red-600"],
];

function CommitteeDashboard() {
  const { token } = useAuth();
  const [dashboard, setDashboard] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    apiRequest("/committee/dashboard", {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then(setDashboard)
      .catch((requestError) => setError(requestError.message));
  }, [token]);

  return (
    <CommitteeLayout
      title="Committee Dashboard"
      description="Review reports, coordinate SOS response, and resolve matched cases across assigned events."
      actions={
        <Link
          to="/committee/reports"
          className="inline-flex h-11 items-center rounded-xl bg-slate-950 px-5 text-sm font-semibold text-white shadow-sm hover:bg-slate-800"
        >
          Review reports
        </Link>
      }
    >
      {error && (
        <div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">
          {error}
        </div>
      )}
      {!dashboard ? (
        <div className="grid min-h-72 place-items-center">
          <LoaderCircle className="size-7 animate-spin text-brand-600" />
        </div>
      ) : (
        <>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
            {kpiConfig.map(([key, label, Icon, style]) => (
              <Card key={key} className="shadow-sm">
                <CardContent className="p-5">
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-sm font-semibold text-slate-500">{label}</p>
                    <span className={`grid size-10 place-items-center rounded-xl ${style}`}>
                      <Icon className="size-5" />
                    </span>
                  </div>
                  <p className="mt-4 text-3xl font-bold tracking-tight text-slate-950">
                    {dashboard.kpis[key]}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>

          <Card className="mt-8 shadow-sm">
            <CardContent className="p-0">
              <div className="flex items-center justify-between border-b border-slate-100 px-6 py-5">
                <div>
                  <h2 className="font-bold text-slate-950">Recent matches</h2>
                  <p className="mt-1 text-xs text-slate-500">Latest candidate pairings</p>
                </div>
                <Link to="/committee/matches" className="text-xs font-bold text-brand-600">
                  View all
                </Link>
              </div>
              {dashboard.recentMatches.length ? (
                <div className="divide-y divide-slate-100">
                  {dashboard.recentMatches.map((match) => (
                    <div key={match._id} className="flex flex-wrap items-center gap-4 px-6 py-4">
                      <span className="grid size-10 place-items-center rounded-xl bg-purple-50 text-purple-600">
                        {match.matchScore}%
                      </span>
                      <div className="min-w-0 flex-1">
                        <p className="truncate text-sm font-bold text-slate-900">
                          {match.missingReportId?.name || "Missing report"} ↔ {match.foundReportId?.helpDesk || "Found report"}
                        </p>
                        <p className="mt-1 text-xs text-slate-500">Generated by committee review</p>
                      </div>
                      <StatusBadge status={match.status} />
                    </div>
                  ))}
                </div>
              ) : (
                <p className="px-6 py-14 text-center text-sm text-slate-500">
                  No matches have been created yet.
                </p>
              )}
            </CardContent>
          </Card>
        </>
      )}
    </CommitteeLayout>
  );
}

export default CommitteeDashboard;
